// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF4CXUbhZdLK7yY_9bmL2eW54j04Oedoc',
    appId: '1:699990478658:web:b866f7feeba002d44602db',
    messagingSenderId: '699990478658',
    projectId: 'moviepop-e2b95',
    authDomain: 'moviepop-e2b95.firebaseapp.com',
    storageBucket: 'moviepop-e2b95.appspot.com',
    measurementId: 'G-GH0KT1S06M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWaXmJs8o48EF5Z5wICu7Q9Xa1_Lbhvbo',
    appId: '1:699990478658:android:35619bbb12b907794602db',
    messagingSenderId: '699990478658',
    projectId: 'moviepop-e2b95',
    storageBucket: 'moviepop-e2b95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7CoQ2LPOBxGsuyqOLTDEIrFhA844B_uA',
    appId: '1:699990478658:ios:dd9faf61102e8dd04602db',
    messagingSenderId: '699990478658',
    projectId: 'moviepop-e2b95',
    storageBucket: 'moviepop-e2b95.appspot.com',
    iosClientId: '699990478658-7mibcesp23e2f9hqa1kjankiaek2j4f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.zpiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7CoQ2LPOBxGsuyqOLTDEIrFhA844B_uA',
    appId: '1:699990478658:ios:dd9faf61102e8dd04602db',
    messagingSenderId: '699990478658',
    projectId: 'moviepop-e2b95',
    storageBucket: 'moviepop-e2b95.appspot.com',
    iosClientId: '699990478658-7mibcesp23e2f9hqa1kjankiaek2j4f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.zpiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF4CXUbhZdLK7yY_9bmL2eW54j04Oedoc',
    appId: '1:699990478658:web:5a0383c35d2f07e64602db',
    messagingSenderId: '699990478658',
    projectId: 'moviepop-e2b95',
    authDomain: 'moviepop-e2b95.firebaseapp.com',
    storageBucket: 'moviepop-e2b95.appspot.com',
    measurementId: 'G-J9WL73Y6Y6',
  );

}